package pdf

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf/v2"
	"steri-connect-go/internal/database"
)

// GenerateCyclePDF generates a PDF document for a cycle protocol
func GenerateCyclePDF(cycle *database.CycleWithDevice) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	// Set font
	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(40, 10, "Sterilization Cycle Protocol")
	pdf.Ln(12)

	// Cycle Header Section
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(40, 8, "Cycle Information")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 10)
	pdf.Cell(50, 6, fmt.Sprintf("Cycle ID: %d", cycle.ID))
	pdf.Ln(6)
	pdf.Cell(50, 6, fmt.Sprintf("Device: %s", cycle.DeviceName))
	pdf.Ln(6)
	pdf.Cell(50, 6, fmt.Sprintf("Device IP: %s", cycle.DeviceIP))
	pdf.Ln(6)
	pdf.Cell(50, 6, fmt.Sprintf("Manufacturer: %s", cycle.Manufacturer))
	pdf.Ln(6)
	pdf.Cell(50, 6, fmt.Sprintf("Program: %s", cycle.Program))
	pdf.Ln(6)
	pdf.Cell(50, 6, fmt.Sprintf("Start Time: %s", cycle.StartTS.Format("2006-01-02 15:04:05")))
	pdf.Ln(6)

	if cycle.EndTS != nil {
		pdf.Cell(50, 6, fmt.Sprintf("End Time: %s", cycle.EndTS.Format("2006-01-02 15:04:05")))
		pdf.Ln(6)
	}

	pdf.Ln(4)

	// Process Parameters Section
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(40, 8, "Process Parameters")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 10)
	if cycle.Phase != "" {
		pdf.Cell(50, 6, fmt.Sprintf("Phase: %s", cycle.Phase))
		pdf.Ln(6)
	}

	if cycle.ProgressPercent != nil {
		pdf.Cell(50, 6, fmt.Sprintf("Progress: %d%%", *cycle.ProgressPercent))
		pdf.Ln(6)
	}

	if cycle.Temperature != nil {
		pdf.Cell(50, 6, fmt.Sprintf("Temperature: %.2f °C", *cycle.Temperature))
		pdf.Ln(6)
	}

	if cycle.Pressure != nil {
		pdf.Cell(50, 6, fmt.Sprintf("Pressure: %.2f bar", *cycle.Pressure))
		pdf.Ln(6)
	}

	pdf.Ln(4)

	// Result Section
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(40, 8, "Result")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 10)
	if cycle.Result != "" {
		resultColor := "green"
		if cycle.Result == "NOK" {
			resultColor = "red"
		}
		pdf.SetTextColor(0, 0, 0)
		if resultColor == "red" {
			pdf.SetTextColor(255, 0, 0)
		} else {
			pdf.SetTextColor(0, 128, 0)
		}
		pdf.Cell(50, 6, fmt.Sprintf("Result: %s", cycle.Result))
		pdf.SetTextColor(0, 0, 0)
		pdf.Ln(6)
	} else {
		pdf.Cell(50, 6, "Result: Pending")
		pdf.Ln(6)
	}

	if cycle.ErrorCode != "" {
		pdf.SetTextColor(255, 0, 0)
		pdf.Cell(50, 6, fmt.Sprintf("Error Code: %s", cycle.ErrorCode))
		pdf.SetTextColor(0, 0, 0)
		pdf.Ln(6)
	}

	if cycle.ErrorDescription != "" {
		pdf.SetTextColor(255, 0, 0)
		pdf.Cell(50, 6, fmt.Sprintf("Error Description: %s", cycle.ErrorDescription))
		pdf.SetTextColor(0, 0, 0)
		pdf.Ln(6)
	}

	pdf.Ln(4)

	// Audit Information Section
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(40, 8, "Audit Information")
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 10)
	pdf.Cell(50, 6, fmt.Sprintf("Protocol Generated: %s", time.Now().Format("2006-01-02 15:04:05")))
	pdf.Ln(6)
	pdf.Cell(50, 6, "Generated By: Steri-Connect System")
	pdf.Ln(6)

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Arial", "I", 8)
	pdf.CellFormat(0, 10, fmt.Sprintf("Page %d", pdf.PageNo()), "", 0, "C", false, 0, "")

	// Generate PDF bytes
	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, fmt.Errorf("failed to generate PDF: %w", err)
	}

	return buf.Bytes(), nil
}

